### ISSUE TITLE
Process exits on Real-time signals

### ISSUE THREAD

**Issue by tellezhector** [un-def/i3blocks-spotify-persist#10]
Hello! First, thanks for i3blocks-mpris, it is pretty cool!

I have come across a bug that I was unable to figure out. My volume blockets rely on real time signals to get "manually" notified on volume changes (via `pkill -RTMIN+10 i3blocks`). This is rather common in [i3blocks](https://github.com/vivien/i3blocks?tab=readme-ov-file#signal) and is explicitely supported.

The bug I came across is that sending any `SIGRTMIN+N` causes `i3blocks-mpris` to exit without any error message, the only trace in standard error is the message `Real-time signal N`, and the exit code is always of the form162+N, where N is the same as in `SIGRTMIN+N`. 

I tried to debug as far as I could but my knowledge on dbus is close to zero.

**Comment by un-def** [comment]
Hello, this is an expected behavior: 

```
SIGNAL(7)
...
The default action for an unhandled real-time signal is to terminate the receiving process.
````


`pkill -RTMIN+10 i3blocks` — this sends the signal to all processes whose process names contain `i3blocks` substring (including `i3blocks-mpris`). What you really want is `pkill -x -RTMIN+10 i3blocks-volume-block` (given your volume blocket is named `i3-blocks-volume-block`):

```
PGREP(1) 
...
       -x, --exact
              Only match processes whose names (or command lines if -f is specified) exactly match the pattern.
```


```
$ pgrep -l i3blocks
2234 i3blocks
2264 i3blocks-mpris

$ pgrep -l -x i3blocks
2234 i3blocks
```

See https://github.com/un-def/i3blocks-mpris/issues/5

**Comment by tellezhector** [comment]
You are right on point!

Thanks for the small lesson on linux's signal handling :+1: 

Closing issue!
